/* ─────────────────────────────────────────────────────────────────
   Semantic relation data for query expansion.
   Source: Wiktionary Thesaurus (synonyms + hyponyms), curated for
   Wikimedia Commons terminology.

   Refresh with:  node scripts/build-synonyms.js
   ───────────────────────────────────────────────────────────────── */

export const SYNONYMS_DATA = {

  // ── Birds ─────────────────────────────────────────────────────────
  bird:       ["fowl", "avian", "songbird", "raptor", "waterfowl", "seabird", "passerine", "aves", "bird of prey"],
  sparrow:    ["house sparrow", "passer domesticus", "finch", "passerine", "songbird"],
  robin:      ["american robin", "turdus migratorius", "european robin", "thrush", "songbird"],
  hawk:       ["falcon", "kestrel", "harrier", "accipiter", "raptor", "bird of prey"],
  eagle:      ["bald eagle", "golden eagle", "accipitridae", "raptor", "bird of prey"],
  owl:        ["barn owl", "great horned owl", "strigiformes", "nocturnal bird", "raptor"],
  parrot:     ["psittacidae", "macaw", "cockatoo", "parakeet", "tropical bird"],
  duck:       ["mallard", "teal", "anas", "waterfowl", "anseriformes", "drake"],
  heron:      ["egret", "great blue heron", "ardea", "wading bird", "ciconiiformes"],
  crow:       ["raven", "jackdaw", "corvidae", "corvus", "corvid"],
  flamingo:   ["phoenicopteridae", "wading bird", "pink bird", "florida bird"],
  pelican:    ["cormorant", "seabird", "pelecanidae", "water bird"],
  pigeon:     ["dove", "rock pigeon", "columba livia", "columbidae", "turtledove"],
  swallow:    ["martin", "hirundine", "hirundo", "swift", "passerine"],
  woodpecker: ["picidae", "picus", "flicker", "tree bird", "drumming bird"],
  penguin:    ["spheniscidae", "flightless bird", "seabird", "antarctic bird"],
  vulture:    ["condor", "buzzard", "new world vulture", "scavenger", "accipitridae"],
  stork:      ["ciconia", "wading bird", "ciconiidae", "migratory bird"],
  kingfisher: ["alcedo", "ceryle", "water bird", "fishing bird"],

  // ── Mammals ───────────────────────────────────────────────────────
  dog:        ["canine", "canis lupus familiaris", "hound", "domestic dog", "puppy", "canidae"],
  cat:        ["feline", "felis catus", "domestic cat", "kitten", "tabby", "felidae"],
  horse:      ["equine", "mare", "stallion", "foal", "pony", "equus caballus", "equidae"],
  rabbit:     ["hare", "lagomorpha", "cottontail", "bunny", "leporidae"],
  squirrel:   ["sciuridae", "chipmunk", "ground squirrel", "tree squirrel", "rodent"],
  bat:        ["chiroptera", "fruit bat", "vampire bat", "microchiroptera", "flying mammal"],
  seal:       ["pinniped", "sea lion", "phocidae", "marine mammal", "fur seal"],
  otter:      ["sea otter", "river otter", "mustelidae", "lutrinae"],
  beaver:     ["castor canadensis", "rodent", "castoridae", "dam builder"],
  rat:        ["mouse", "rodent", "muridae", "vermin"],
  hedgehog:   ["erinaceidae", "erinaceus", "spiny mammal"],
  elephant:   ["elephantidae", "tusker", "proboscidea", "pachyderm", "african elephant"],
  tiger:      ["panthera tigris", "feline", "big cat", "bengal tiger", "siberian tiger"],
  lion:       ["panthera leo", "big cat", "felidae", "pride", "african lion"],
  bear:       ["ursidae", "grizzly", "brown bear", "polar bear", "black bear", "ursus"],
  wolf:       ["canis lupus", "grey wolf", "timber wolf", "pack wolf", "canidae"],
  fox:        ["vulpes", "red fox", "reynard", "canidae", "fennec"],
  deer:       ["cervidae", "stag", "doe", "reindeer", "elk", "antler", "odocoileus"],
  gorilla:    ["ape", "primate", "great ape", "gorilla gorilla", "mountain gorilla"],
  chimpanzee: ["pan troglodytes", "ape", "primate", "great ape"],
  dolphin:    ["porpoise", "cetacean", "tursiops", "marine mammal", "bottlenose"],
  whale:      ["cetacean", "humpback whale", "blue whale", "baleen whale", "sperm whale"],
  shark:      ["selachii", "great white shark", "hammerhead", "bull shark", "cartilaginous fish"],
  crocodile:  ["alligator", "caiman", "crocodylidae", "reptile", "crocodylus"],
  monkey:     ["primate", "simian", "macaque", "capuchin", "marmoset", "ape"],
  giraffe:    ["giraffa camelopardalis", "bovidae", "ruminant", "savanna animal"],
  zebra:      ["equidae", "equus zebra", "stripe", "savanna animal"],
  rhinoceros: ["rhino", "rhinocerotidae", "megafauna", "horn"],
  hippopotamus: ["hippo", "hippopotamidae", "river horse", "amphibious mammal"],
  camel:      ["dromedary", "bactrian", "camelidae", "desert animal", "hump"],

  // ── Reptiles & Amphibians ──────────────────────────────────────────
  snake:      ["serpent", "viper", "cobra", "python", "boa", "ophidia", "reptile"],
  lizard:     ["gecko", "iguana", "chameleon", "skink", "lacertilia", "reptile"],
  turtle:     ["tortoise", "terrapin", "chelonia", "testudines", "sea turtle"],
  frog:       ["toad", "anuran", "amphibian", "tree frog", "bullfrog", "ranidae"],
  salamander: ["newt", "caudata", "amphibian", "axolotl", "plethodon"],

  // ── Insects & Invertebrates ───────────────────────────────────────
  butterfly:  ["moth", "lepidoptera", "caterpillar", "chrysalis", "insect"],
  bee:        ["honeybee", "bumblebee", "apis", "apidae", "pollinator", "insect"],
  beetle:     ["coleoptera", "ladybug", "ladybird", "scarab", "insect"],
  spider:     ["arachnid", "tarantula", "orb weaver", "wolf spider"],
  ant:        ["formicidae", "fire ant", "carpenter ant", "colony insect"],
  dragonfly:  ["damselfly", "odonata", "libellula", "aquatic insect"],

  // ── Marine Life ────────────────────────────────────────────────────
  fish:       ["pisces", "aquatic animal", "freshwater fish", "marine fish", "ichthyology"],
  salmon:     ["trout", "salmonidae", "anadromous fish", "atlantic salmon", "pacific salmon"],
  coral:      ["coral reef", "cnidaria", "polyp", "marine invertebrate", "reef"],
  jellyfish:  ["medusa", "cnidaria", "sea jelly", "marine invertebrate"],
  crab:       ["crustacean", "decapoda", "lobster", "shrimp", "brachyura"],
  octopus:    ["cephalopod", "mollusca", "squid", "cuttlefish"],
  starfish:   ["sea star", "echinoderm", "asteroidea", "marine invertebrate"],

  // ── Plants ─────────────────────────────────────────────────────────
  tree:       ["forest", "woodland", "arboreal", "arbor", "canopy", "timber", "dendrology"],
  flower:     ["blossom", "bloom", "petal", "flora", "wildflower", "angiosperm", "floret"],
  grass:      ["meadow", "prairie", "poaceae", "turf", "lawn", "graminoid"],
  mushroom:   ["fungus", "fungi", "toadstool", "mycelium", "mycology", "spore"],
  fern:       ["pteridophyte", "frond", "bracken", "polypodium"],
  moss:       ["bryophyte", "liverwort", "lichen", "saxicolous"],
  rose:       ["rosa", "wild rose", "rosaceae", "dog rose", "shrub"],
  oak:        ["quercus", "deciduous tree", "acorn", "hardwood", "holm oak"],
  palm:       ["arecaceae", "coconut palm", "date palm", "tropical tree"],
  cactus:     ["succulent", "desert plant", "xerophyte", "cactaceae", "opuntia"],
  bamboo:     ["bambusoideae", "poaceae", "giant bamboo", "tropical plant"],
  seaweed:    ["algae", "kelp", "marine plant", "macroalgae"],
  sunflower:  ["helianthus", "asteraceae", "annual flower"],
  lily:       ["liliaceae", "water lily", "tiger lily", "bulb flower"],
  orchid:     ["orchidaceae", "epiphyte", "tropical flower"],
  tulip:      ["liliaceae", "tulipa", "spring flower", "bulb"],
  wheat:      ["grain", "cereal", "triticum", "poaceae", "crop"],
  rice:       ["oryza sativa", "paddy", "grain", "cereal", "poaceae"],
  lavender:   ["lavendula", "herb", "fragrant plant", "purple flower"],
  pine:       ["conifer", "pinus", "evergreen", "fir", "spruce", "needle tree"],

  // ── Geography ──────────────────────────────────────────────────────
  mountain:   ["peak", "summit", "alpine", "massif", "highland", "range", "ridge"],
  river:      ["stream", "creek", "tributary", "waterway", "brook", "torrent", "watercourse"],
  lake:       ["pond", "reservoir", "loch", "lagoon", "tarn", "freshwater body"],
  ocean:      ["sea", "marine", "pelagic", "seawater", "maritime", "brine"],
  desert:     ["arid", "sand dune", "dunes", "steppe", "badlands", "dryland"],
  forest:     ["woodland", "jungle", "rainforest", "grove", "boreal forest", "woods"],
  island:     ["archipelago", "atoll", "isle", "islet", "peninsula"],
  glacier:    ["ice cap", "ice field", "iceberg", "ice sheet", "crevasse", "moraine"],
  cave:       ["cavern", "grotto", "karst", "stalactite", "stalagmite", "underground"],
  canyon:     ["gorge", "ravine", "chasm", "valley", "escarpment", "gulch"],
  waterfall:  ["cascade", "cataract", "falls", "plunge pool", "chute"],
  coast:      ["shore", "beach", "shoreline", "cliffs", "seaside", "littoral"],
  valley:     ["dale", "glen", "rift valley", "lowland", "depression"],
  swamp:      ["marsh", "wetland", "bog", "fen", "mangrove", "bayou"],
  cliff:      ["escarpment", "bluff", "precipice", "crag", "promontory"],
  dune:       ["sand dune", "barchan", "coastal dune", "desert dune", "erg"],
  tundra:     ["permafrost", "arctic plain", "taiga", "boreal", "subarctic"],
  savanna:    ["grassland", "prairie", "veld", "pampa", "steppe"],
  reef:       ["coral reef", "barrier reef", "fringing reef", "atoll", "marine habitat"],

  // ── Weather ────────────────────────────────────────────────────────
  rain:       ["rainfall", "precipitation", "shower", "downpour", "drizzle", "monsoon"],
  snow:       ["snowfall", "blizzard", "snowflake", "frost", "sleet", "hail", "ice"],
  storm:      ["tempest", "gale", "squall", "nor'easter", "derecho"],
  cloud:      ["cumulus", "stratus", "nimbus", "cirrus", "overcast", "cloudscape"],
  fog:        ["mist", "haze", "brume", "haar", "sea mist", "vapor"],
  lightning:  ["thunderbolt", "thunder", "electrical discharge", "ball lightning"],
  tornado:    ["twister", "waterspout", "funnel cloud", "whirlwind"],
  hurricane:  ["typhoon", "tropical storm", "cyclone", "gale force"],
  rainbow:    ["arc-en-ciel", "spectrum", "refraction", "atmospheric optics"],
  aurora:     ["aurora borealis", "northern lights", "aurora australis", "polar aurora", "southern lights"],
  flood:      ["inundation", "deluge", "overflow", "flash flood", "alluvion"],

  // ── Music ──────────────────────────────────────────────────────────
  song:       ["melody", "tune", "composition", "air", "ballad", "refrain", "chanson"],
  music:      ["composition", "recording", "performance", "harmony", "musical piece"],
  guitar:     ["acoustic guitar", "electric guitar", "stringed instrument", "lute", "ukulele"],
  piano:      ["keyboard instrument", "harpsichord", "pianoforte", "clavichord", "grand piano"],
  violin:     ["fiddle", "viola", "cello", "stringed instrument", "bowed instrument"],
  drum:       ["percussion", "timpani", "djembe", "tabla", "snare drum", "bass drum"],
  flute:      ["woodwind", "fife", "recorder", "transverse flute", "pan pipe"],
  trumpet:    ["horn", "brass instrument", "cornet", "bugle", "trombone"],
  harp:       ["lyre", "plucked instrument", "celtic harp", "kora"],
  organ:      ["pipe organ", "hammond organ", "church organ", "keyboard"],
  opera:      ["aria", "soprano", "tenor", "baritone", "libretto", "lyric opera"],
  orchestra:  ["symphony orchestra", "chamber ensemble", "philharmonic", "chamber music"],
  choir:      ["chorus", "choral", "a cappella", "vocal ensemble", "chorale"],
  dance:      ["ballet", "waltz", "tango", "flamenco", "choreography", "ballroom"],
  blues:      ["rhythm and blues", "soul music", "gospel", "delta blues"],
  lute:       ["theorbo", "mandolin", "oud", "cittern", "plucked instrument"],
  accordion:  ["concertina", "melodeon", "squeeze box", "reed instrument"],
  bagpipe:    ["uilleann pipe", "gaita", "dudelsack", "wind instrument"],
  sitar:      ["indian classical music", "raga", "plucked instrument", "sarod"],
  tabla:      ["dhol", "mridangam", "indian drum", "percussion", "south asian music"],

  // ── History & Architecture ─────────────────────────────────────────
  castle:     ["fortress", "citadel", "fortification", "medieval fortress", "rampart", "battlement"],
  church:     ["cathedral", "basilica", "chapel", "abbey", "monastery", "sanctuary", "nave"],
  mosque:     ["masjid", "minaret", "islamic architecture", "mihrab", "dome"],
  temple:     ["shrine", "sanctuary", "pagoda", "ziggurat", "stupa", "naos"],
  pyramid:    ["ancient egypt", "burial chamber", "megalith", "necropolis", "mastaba"],
  ruins:      ["ancient ruins", "archaeological site", "remnants", "historic site", "excavation"],
  bridge:     ["viaduct", "aqueduct", "arch bridge", "suspension bridge", "span"],
  lighthouse: ["beacon", "maritime tower", "pharos", "coastal tower"],
  palace:     ["château", "manor", "royal residence", "stately home", "court"],
  monument:   ["memorial", "obelisk", "cenotaph", "statue", "landmark"],
  coin:       ["numismatics", "currency", "medal", "token", "medallion"],
  manuscript: ["codex", "scroll", "illuminated manuscript", "parchment", "papyrus"],
  map:        ["cartography", "atlas", "chart", "topographic map", "portolan"],
  sword:      ["blade", "saber", "rapier", "cutlass", "scimitar", "dagger"],
  armor:      ["armour", "mail", "chainmail", "breastplate", "helmet", "knight"],
  aqueduct:   ["roman engineering", "water supply", "arch structure"],
  amphitheater: ["colosseum", "arena", "roman theater", "ancient theater"],

  // ── Science & Astronomy ───────────────────────────────────────────
  star:       ["stellar", "constellation", "nova", "supernova", "celestial body", "sun"],
  planet:     ["solar system", "orbit", "celestial body", "exoplanet", "terrestrial planet"],
  galaxy:     ["nebula", "cosmos", "universe", "spiral galaxy", "milky way", "cluster"],
  comet:      ["asteroid", "meteor", "meteorite", "bolide", "space rock", "tail"],
  moon:       ["lunar", "satellite", "crater", "full moon", "crescent", "lunar surface"],
  crystal:    ["mineral", "gemstone", "quartz", "calcite", "mineralogy", "gem"],
  fossil:     ["paleontology", "prehistoric", "specimen", "ancient remains", "bone"],
  atom:       ["molecule", "nucleus", "electron", "element", "chemistry"],
  diamond:    ["gemstone", "carbon crystal", "precious stone", "gem"],
  nebula:     ["interstellar cloud", "supernova remnant", "planetary nebula", "emission nebula"],
  volcano:    ["volcanic", "lava flow", "caldera", "magma", "cinder cone", "eruption"],
  cell:       ["biology", "organelle", "nucleus", "membrane", "cytoplasm", "microbiology"],
  dna:        ["gene", "chromosome", "genome", "helix", "nucleotide", "genetics"],
  microscope: ["laboratory", "magnification", "optical instrument", "electron microscope"],

  // ── Art & Visual ──────────────────────────────────────────────────
  painting:   ["artwork", "canvas", "oil painting", "watercolor", "acrylic", "fresco"],
  sculpture:  ["statue", "figurine", "carving", "bronze", "marble", "clay", "relief"],
  drawing:    ["sketch", "illustration", "engraving", "etching", "charcoal", "ink"],
  photograph: ["photo", "snapshot", "photographic print", "daguerreotype", "silver gelatin"],
  mosaic:     ["tesserae", "byzantine mosaic", "floor mosaic", "opus sectile", "tile"],
  mural:      ["fresco", "wall painting", "graffiti art", "trompe l'oeil", "stencil"],
  tapestry:   ["textile art", "weaving", "arras", "carpet", "woven wall hanging"],
  print:      ["woodcut", "lithograph", "screen print", "etching", "engraving"],
  pottery:    ["ceramics", "earthenware", "stoneware", "porcelain", "kiln"],
  textile:    ["fabric", "cloth", "weaving", "loom", "embroidery", "tapestry"],

  // ── Human Activities & Transport ──────────────────────────────────
  boat:       ["vessel", "ship", "canoe", "kayak", "sailboat", "rowboat", "nautical"],
  sailing:    ["yacht", "regatta", "maritime", "sail", "rigging", "nautical"],
  fishing:    ["angling", "fly fishing", "deep sea fishing", "net fishing", "piscatorial"],
  farming:    ["agriculture", "cultivation", "harvest", "crop", "plowing", "tillage"],
  climbing:   ["mountaineering", "rock climbing", "alpinism", "bouldering", "ascent"],
  cycling:    ["bicycle", "bike", "velodrome", "road cycling", "mountain biking"],
  swimming:   ["aquatics", "natation", "swim", "open water", "freestyle"],
  market:     ["bazaar", "souk", "marketplace", "fair", "trade", "bazar"],
  festival:   ["carnival", "celebration", "parade", "feast", "fiesta", "fête"],
  wedding:    ["marriage", "ceremony", "bride", "groom", "nuptial"],
  prayer:     ["worship", "devotion", "ritual", "meditation", "contemplation"],
  harvest:    ["reaping", "crop gathering", "threshing", "vintage", "gleaning"],

};
