/* ─────────────────────────────────────────────────────────────────
   Browse-by-Topic taxonomy (12 categories).
   Each topic:    { id, label, lcClass, icon, headings[] }
   Each heading:  { label, lcsh, query }
   `icon` renders the LC class letter as a card-catalog spine label.
   ───────────────────────────────────────────────────────────────── */

const lcMark = (cls) => `<span class="topic-lc-mark">${cls}</span>`;

export const TOPICS = [

  {
    id: "natural-history",
    label: "Natural History",
    lcClass: "Q",
    icon: lcMark("Q"),
    headings: [
      { label: "Animal Behavior",                lcsh: "Animal behavior",          query: "animal behavior OR ethology OR animal social behavior" },
      { label: "Arachnids",                      lcsh: "Arachnida",                query: "spider OR arachnid OR scorpion" },
      { label: "Birds",                          lcsh: "Birds",                    query: "birds OR aves OR ornithology" },
      { label: "Conservation & Endangered Species", lcsh: "Endangered species",    query: "endangered species OR wildlife conservation OR rare species" },
      { label: "Crustaceans",                    lcsh: "Crustacea",                query: "crustacean OR crab OR lobster OR shrimp" },
      { label: "Ecology & Habitats",             lcsh: "Ecology",                  query: "ecology OR habitat OR ecosystem OR biome" },
      { label: "Fish",                           lcsh: "Fishes",                   query: "fishes OR fish species OR ichthyology" },
      { label: "Flowering Plants",               lcsh: "Angiosperms",              query: "flowering plants OR angiosperms OR wildflowers" },
      { label: "Fossils & Paleontology",         lcsh: "Paleontology",             query: "fossils OR paleontology OR prehistoric life" },
      { label: "Fungi & Lichens",                lcsh: "Fungi",                    query: "fungi OR mushrooms OR lichens" },
      { label: "Insects",                        lcsh: "Insects",                  query: "insects OR entomology OR insecta" },
      { label: "Mammals",                        lcsh: "Mammals",                  query: "mammals OR mammalia OR wildlife mammals" },
      { label: "Marine Life",                    lcsh: "Marine animals",           query: "marine animals OR sea creatures OR ocean life" },
      { label: "Marine Mammals",                 lcsh: "Marine mammals",           query: "whales OR dolphins OR seals OR marine mammals" },
      { label: "Mollusks",                       lcsh: "Mollusks",                 query: "mollusk OR snail OR octopus OR nautilus" },
      { label: "Mosses & Ferns",                 lcsh: "Mosses",                   query: "moss OR fern OR bryophyte OR pteridophyte" },
      { label: "Reptiles & Amphibians",          lcsh: "Reptiles",                 query: "reptiles OR amphibians OR herpetology" },
      { label: "Trees & Shrubs",                 lcsh: "Trees",                    query: "trees OR shrubs OR dendrology" },
    ],
  },

  {
    id: "landscapes-earth",
    label: "Landscapes & Earth",
    lcClass: "G",
    icon: lcMark("G"),
    headings: [
      { label: "Aerial Views",         lcsh: "Aerial photography",   query: "aerial photography OR aerial view OR landscape from above" },
      { label: "Canyons & Valleys",    lcsh: "Canyons",              query: "canyon OR valley OR gorge OR ravine" },
      { label: "Caves",                lcsh: "Caves",                query: "caves OR caverns OR speleology" },
      { label: "Cliffs",               lcsh: "Cliffs",               query: "cliff OR sea cliff OR escarpment" },
      { label: "Coasts & Shorelines",  lcsh: "Coasts",               query: "coasts OR shoreline OR coastal landscape" },
      { label: "Deserts",              lcsh: "Deserts",              query: "deserts OR arid landscape OR desert terrain" },
      { label: "Forests",              lcsh: "Forests and forestry", query: "forests OR woodland OR forest landscape" },
      { label: "Glaciers & Ice",       lcsh: "Glaciers",             query: "glaciers OR ice sheets OR iceberg OR polar landscape" },
      { label: "Islands",              lcsh: "Islands",              query: "islands OR island geography OR archipelago" },
      { label: "Lakes",                lcsh: "Lakes",                query: "lake OR alpine lake OR mountain lake" },
      { label: "Mountains",            lcsh: "Mountains",            query: "mountains OR mountain range OR alpine landscape" },
      { label: "Rainforests",          lcsh: "Rain forests",         query: "rainforest OR tropical forest OR jungle" },
      { label: "Rivers & Streams",     lcsh: "Rivers",               query: "rivers OR streams OR waterways" },
      { label: "Savanna & Grasslands", lcsh: "Grasslands",           query: "savanna OR grassland OR prairie OR steppe" },
      { label: "Tundra",               lcsh: "Tundras",              query: "tundra OR arctic landscape OR taiga" },
      { label: "Volcanoes",            lcsh: "Volcanoes",            query: "volcanoes OR volcanic eruption OR lava OR caldera" },
      { label: "Waterfalls",           lcsh: "Waterfalls",           query: "waterfall OR cascade OR falls" },
      { label: "Wetlands",             lcsh: "Wetlands",             query: "wetlands OR marshes OR swamps OR bogs" },
    ],
  },

  {
    id: "astronomy",
    label: "Astronomy",
    lcClass: "QB",
    icon: lcMark("QB"),
    headings: [
      { label: "Astronauts",                lcsh: "Astronauts",                query: "astronaut OR cosmonaut OR human spaceflight" },
      { label: "Astrophotography",          lcsh: "Astronomical photography",  query: "astrophotography OR deep space photo OR night sky photography" },
      { label: "Black Holes",               lcsh: "Black holes (Astronomy)",   query: "black hole OR event horizon OR singularity" },
      { label: "Comets & Asteroids",        lcsh: "Comets",                    query: "comets OR asteroids OR minor planets OR meteorites" },
      { label: "Constellations",            lcsh: "Constellations",            query: "constellations OR star map OR celestial chart" },
      { label: "Cosmology",                 lcsh: "Cosmology",                 query: "cosmology OR universe OR big bang OR cosmic background" },
      { label: "Exoplanets",                lcsh: "Extrasolar planets",        query: "exoplanet OR extrasolar planet OR alien world" },
      { label: "Galaxies",                  lcsh: "Galaxies",                  query: "galaxies OR galaxy OR extragalactic" },
      { label: "Jupiter & Saturn",          lcsh: "Jupiter (Planet)",          query: "Jupiter OR Saturn OR gas giant" },
      { label: "Mars",                      lcsh: "Mars (Planet)",             query: "Mars planet OR Martian surface OR Mars exploration" },
      { label: "Nebulae",                   lcsh: "Nebulae",                   query: "nebulae OR nebula OR interstellar cloud" },
      { label: "Solar System",              lcsh: "Solar system",              query: "solar system OR planets OR planetary science" },
      { label: "Space Exploration",         lcsh: "Astronautics",              query: "space exploration OR spacecraft OR space mission" },
      { label: "Stars",                     lcsh: "Stars",                     query: "stars OR stellar OR star cluster" },
      { label: "Supernovas",                lcsh: "Supernovae",                query: "supernova OR stellar explosion OR exploding star" },
      { label: "Telescopes & Observatories", lcsh: "Telescopes",               query: "telescope OR observatory OR astronomical instrument" },
      { label: "The Moon",                  lcsh: "Moon",                      query: "moon OR lunar surface OR lunar geology" },
      { label: "The Sun",                   lcsh: "Sun",                       query: "sun OR solar corona OR sunspot" },
    ],
  },

  {
    id: "fine-arts",
    label: "Fine Arts",
    lcClass: "N",
    icon: lcMark("N"),
    headings: [
      { label: "Calligraphy",           lcsh: "Calligraphy",                  query: "calligraphy OR Islamic calligraphy OR Chinese calligraphy" },
      { label: "Caricature",            lcsh: "Caricatures and cartoons",     query: "caricature OR political cartoon OR satirical drawing" },
      { label: "Drawing & Sketching",   lcsh: "Drawing",                      query: "drawing OR sketch OR charcoal art" },
      { label: "Frescoes",              lcsh: "Mural painting and decoration", query: "fresco OR fresco painting OR Italian fresco" },
      { label: "Genre Painting",        lcsh: "Genre painting",               query: "genre painting OR everyday life painting" },
      { label: "History Painting",      lcsh: "History painting",             query: "history painting OR historical painting OR battle scene painting" },
      { label: "Illustration",          lcsh: "Illustration of books",        query: "illustration OR book illustration OR decorative illustration" },
      { label: "Landscape Painting",    lcsh: "Landscape painting",           query: "landscape painting OR landscape art OR plein air" },
      { label: "Miniature Painting",    lcsh: "Miniature painting",           query: "miniature painting OR illuminated manuscript OR Persian miniature" },
      { label: "Mosaics",               lcsh: "Mosaics",                      query: "mosaic OR tessera OR Byzantine mosaic OR Roman mosaic" },
      { label: "Murals",                lcsh: "Mural painting and decoration", query: "mural OR wall painting OR public mural" },
      { label: "Painting",              lcsh: "Painting",                     query: "painting OR oil painting OR canvas art" },
      { label: "Pastels",               lcsh: "Pastel drawing",               query: "pastel drawing OR pastel painting OR chalk pastel" },
      { label: "Photography (Fine Art)", lcsh: "Photography, Artistic",       query: "artistic photography OR fine art photography" },
      { label: "Portrait Art",          lcsh: "Portrait painting",            query: "portrait painting OR portraiture OR painted portrait" },
      { label: "Printmaking",           lcsh: "Prints",                       query: "prints OR printmaking OR engraving OR etching OR woodcut" },
      { label: "Religious Art",         lcsh: "Christian art and symbolism",  query: "religious art OR devotional painting OR altarpiece" },
      { label: "Sculpture",             lcsh: "Sculpture",                    query: "sculpture OR sculptural art OR statue OR carving" },
      { label: "Still Life",            lcsh: "Still-life painting",          query: "still life OR still-life painting OR nature morte" },
      { label: "Watercolor",            lcsh: "Watercolor painting",          query: "watercolor OR watercolour OR aquarelle" },
    ],
  },

  {
    id: "architecture",
    label: "Architecture",
    lcClass: "NA",
    icon: lcMark("NA"),
    headings: [
      { label: "Ancient Architecture",      lcsh: "Architecture, Ancient",     query: "ancient architecture OR Greek temple OR Roman architecture" },
      { label: "Architectural Drawings",    lcsh: "Architectural drawing",     query: "architectural drawing OR blueprint OR architectural rendering" },
      { label: "Art Deco",                  lcsh: "Architecture, Art deco",    query: "Art Deco architecture OR Streamline Moderne" },
      { label: "Art Nouveau",               lcsh: "Architecture, Art nouveau", query: "Art Nouveau architecture OR Jugendstil OR Secession architecture" },
      { label: "Asian Architecture",        lcsh: "Architecture, East Asian",  query: "Asian architecture OR pagoda OR Chinese architecture OR Japanese architecture" },
      { label: "Baroque Architecture",      lcsh: "Architecture, Baroque",     query: "baroque architecture OR baroque church OR baroque palace" },
      { label: "Bridges",                   lcsh: "Bridges",                   query: "bridge OR historic bridge OR stone bridge OR viaduct" },
      { label: "Castles & Fortifications",  lcsh: "Castles",                   query: "castle OR fortification OR medieval fortress" },
      { label: "Churches & Cathedrals",     lcsh: "Church architecture",       query: "church OR cathedral OR basilica" },
      { label: "Civic Buildings",           lcsh: "Public buildings",          query: "public building OR civic architecture OR city hall" },
      { label: "Domestic Architecture",     lcsh: "Architecture, Domestic",    query: "domestic architecture OR historic house OR manor house" },
      { label: "Egyptian Architecture",     lcsh: "Architecture, Egyptian",    query: "Egyptian architecture OR pyramid OR ancient Egyptian temple" },
      { label: "Islamic Architecture",      lcsh: "Architecture, Islamic",     query: "Islamic architecture OR mosque OR madrasa OR minaret" },
      { label: "Lighthouses",               lcsh: "Lighthouses",               query: "lighthouse OR coastal lighthouse OR maritime beacon" },
      { label: "Medieval Architecture",     lcsh: "Architecture, Medieval",    query: "medieval architecture OR gothic cathedral OR romanesque" },
      { label: "Modern Architecture",       lcsh: "Architecture, Modern",      query: "modern architecture OR modernist building OR 20th century architecture" },
      { label: "Mosques",                   lcsh: "Mosques",                   query: "mosque OR jami OR masjid OR Islamic place of worship" },
      { label: "Renaissance Architecture",  lcsh: "Architecture, Renaissance", query: "Renaissance architecture OR classical revival OR palazzo" },
      { label: "Towers",                    lcsh: "Towers",                    query: "tower OR bell tower OR clock tower OR watchtower" },
      { label: "Vernacular Architecture",   lcsh: "Vernacular architecture",   query: "vernacular architecture OR traditional building OR folk architecture" },
    ],
  },

  {
    id: "decorative-arts",
    label: "Decorative Arts",
    lcClass: "NK",
    icon: lcMark("NK"),
    headings: [
      { label: "Arms & Armor",           lcsh: "Arms and armor",         query: "arms and armor OR sword OR helmet OR historic weapon" },
      { label: "Bookbinding",            lcsh: "Bookbinding",            query: "bookbinding OR decorative binding OR historic bookcover" },
      { label: "Ceramics & Pottery",     lcsh: "Ceramics",               query: "ceramics OR pottery OR earthenware OR porcelain" },
      { label: "Cloisonné & Enamels",    lcsh: "Enamel and enameling",   query: "cloisonné OR enamel OR champlevé" },
      { label: "Coins & Medals",         lcsh: "Coins",                  query: "coin OR medal OR ancient coin OR commemorative medal" },
      { label: "Embroidery & Needlework", lcsh: "Embroidery",            query: "embroidery OR needlework OR decorative stitching" },
      { label: "Furniture",              lcsh: "Furniture",              query: "furniture OR historic furniture OR antique furniture" },
      { label: "Glassware",              lcsh: "Glassware",              query: "glassware OR art glass OR decorative glass" },
      { label: "Jewelry",                lcsh: "Jewelry",                query: "jewelry OR jewellery OR ornamental adornment" },
      { label: "Lacework",               lcsh: "Lace and lace making",   query: "lace OR lacework OR bobbin lace OR needle lace" },
      { label: "Lacquerwork",            lcsh: "Lacquer and lacquering", query: "lacquerwork OR lacquer art OR Japanese lacquer" },
      { label: "Metalwork",              lcsh: "Metal-work",             query: "metalwork OR wrought iron OR decorative metalwork" },
      { label: "Quilts",                 lcsh: "Quilts",                 query: "quilt OR patchwork quilt OR American quilt" },
      { label: "Rugs & Carpets",         lcsh: "Rugs",                   query: "rug OR carpet OR oriental rug OR Persian carpet" },
      { label: "Stained Glass",          lcsh: "Glass painting and staining", query: "stained glass OR leaded glass OR church window" },
      { label: "Tapestries",             lcsh: "Tapestry",               query: "tapestry OR woven tapestry OR Flemish tapestry" },
      { label: "Textiles & Weaving",     lcsh: "Textile fabrics",        query: "textile OR woven fabric OR weaving" },
      { label: "Watches & Clocks",       lcsh: "Clocks and watches",     query: "clock OR watch OR timepiece OR antique clock" },
      { label: "Wood Carving",           lcsh: "Wood-carving",           query: "wood carving OR woodwork OR carved wood" },
    ],
  },

  {
    id: "music",
    label: "Music",
    lcClass: "M",
    icon: lcMark("M"),
    headings: [
      { label: "Ballet & Dance",                  lcsh: "Ballet",                 query: "ballet OR classical dance OR dance performance" },
      { label: "Classical Music",                 lcsh: "Music",                  query: "classical music OR orchestral music OR concert music" },
      { label: "Concerts & Performances",         lcsh: "Concerts",               query: "concert OR music performance OR recital" },
      { label: "Ensembles",                       lcsh: "Musical ensembles",      query: "orchestra OR musical ensemble OR chamber music" },
      { label: "Ensembles — Marching Bands",      lcsh: "Bands (Music)",          query: "marching band OR military band OR brass band" },
      { label: "Folk Music",                      lcsh: "Folk music",             query: "folk music OR traditional music OR world music" },
      { label: "Instruments — Brass",             lcsh: "Brass instruments",      query: "brass instrument OR trumpet OR trombone OR horn" },
      { label: "Instruments — Keyboard",          lcsh: "Keyboard instruments",   query: "keyboard instrument OR piano OR harpsichord OR organ" },
      { label: "Instruments — Percussion",        lcsh: "Percussion instruments", query: "percussion instrument OR drum OR xylophone OR timpani" },
      { label: "Instruments — Strings",           lcsh: "Stringed instruments",   query: "stringed instrument OR violin OR cello OR lute" },
      { label: "Instruments — Woodwinds",         lcsh: "Wind instruments",       query: "wind instrument OR flute OR oboe OR clarinet" },
      { label: "Jazz & Blues",                    lcsh: "Jazz",                   query: "jazz OR blues OR jazz band OR jazz musician" },
      { label: "Music History",                   lcsh: "Music--History",         query: "music history OR historical musicology OR composer portrait" },
      { label: "Music Manuscripts",               lcsh: "Music manuscripts",      query: "music manuscript OR musical score OR sheet music" },
      { label: "Musical Instruments",             lcsh: "Musical instruments",    query: "musical instrument OR stringed instrument OR wind instrument OR brass instrument OR percussion instrument OR keyboard instrument" },
      { label: "Musical Notation",                lcsh: "Musical notation",       query: "musical notation OR music score OR notated music" },
      { label: "Opera",                           lcsh: "Opera",                  query: "opera OR operatic performance OR opera house" },
      { label: "Operetta & Musical Theater",      lcsh: "Musicals",               query: "operetta OR musical theater OR Broadway musical" },
      { label: "Sacred & Choral Music",           lcsh: "Sacred music",           query: "sacred music OR choral music OR hymn OR Gregorian chant" },
    ],
  },

  {
    id: "history",
    label: "History",
    lcClass: "D",
    icon: lcMark("D"),
    headings: [
      { label: "African History",            lcsh: "Africa--History",              query: "African history OR sub-Saharan Africa history OR African civilization" },
      { label: "Age of Exploration",         lcsh: "Discoveries (in geography)",   query: "age of exploration OR voyage of discovery OR explorers" },
      { label: "American History",           lcsh: "United States--History",       query: "American history OR United States history OR US historical" },
      { label: "Ancient Civilizations",      lcsh: "Civilization, Ancient",        query: "ancient civilization OR ancient world OR antiquity" },
      { label: "Ancient Egypt",              lcsh: "Egypt--Civilization",          query: "ancient Egypt OR Egyptian civilization OR pharaonic Egypt" },
      { label: "Ancient Greece",             lcsh: "Greece--History--To 146 B.C.", query: "ancient Greece OR Greek history OR Hellenic civilization" },
      { label: "Ancient Rome",               lcsh: "Rome--History",                query: "ancient Rome OR Roman history OR Roman Empire" },
      { label: "Asian History",              lcsh: "Asia--History",                query: "Asian history OR East Asia history OR Asian civilization" },
      { label: "Byzantine Empire",           lcsh: "Byzantine Empire",             query: "Byzantine Empire OR Constantinople OR Eastern Roman" },
      { label: "Cold War",                   lcsh: "Cold War",                     query: "Cold War OR Iron Curtain OR Soviet-American" },
      { label: "Colonial History",           lcsh: "Colonies",                     query: "colonial history OR colonialism OR colonial era" },
      { label: "Crusades",                   lcsh: "Crusades",                     query: "Crusades OR crusader OR medieval Holy Land" },
      { label: "Latin American History",     lcsh: "Latin America--History",       query: "Latin American history OR South American history OR pre-Columbian" },
      { label: "Medieval Period",            lcsh: "Middle Ages",                  query: "Middle Ages OR medieval history OR medieval Europe" },
      { label: "Renaissance & Reformation",  lcsh: "Renaissance",                  query: "Renaissance OR Reformation OR Protestant Reformation" },
      { label: "Revolutions",                lcsh: "Revolutions",                  query: "revolution OR revolutionary war OR political revolution" },
      { label: "Russian History",            lcsh: "Russia--History",              query: "Russian history OR Imperial Russia OR Soviet Union history" },
      { label: "Vikings",                    lcsh: "Vikings",                      query: "Vikings OR Norse OR Viking Age" },
      { label: "World War I",                lcsh: "World War, 1914-1918",         query: "World War I OR First World War OR WWI" },
      { label: "World War II",               lcsh: "World War, 1939-1945",         query: "World War II OR Second World War OR WWII" },
    ],
  },

  {
    id: "maps-cartography",
    label: "Maps & Cartography",
    lcClass: "GA",
    icon: lcMark("GA"),
    headings: [
      { label: "Atlas Pages",        lcsh: "Atlases",                     query: "atlas OR geographic atlas OR cartographic atlas" },
      { label: "Aviation Charts",    lcsh: "Aeronautical charts",         query: "aeronautical chart OR aviation map OR sectional chart" },
      { label: "Cartographic Art",   lcsh: "Decorative maps",             query: "decorative map OR cartouche OR ornamental map" },
      { label: "Celestial Charts",   lcsh: "Stars--Maps",                 query: "celestial map OR star chart OR astronomical map" },
      { label: "City Plans",         lcsh: "Cities and towns--Maps",      query: "city map OR city plan OR urban cartography" },
      { label: "Globes",             lcsh: "Globes",                      query: "globe OR terrestrial globe OR celestial globe" },
      { label: "Historical Maps",    lcsh: "Historical maps",             query: "historical map OR antique map OR old map" },
      { label: "Manuscript Maps",    lcsh: "Maps, Manuscript",            query: "manuscript map OR hand-drawn map OR cartographic manuscript" },
      { label: "Map Projections",    lcsh: "Map projection",              query: "map projection OR Mercator OR Robinson projection" },
      { label: "Maps of Antiquity",  lcsh: "Cartography, Ancient",        query: "ancient map OR Ptolemy map OR Roman cartography" },
      { label: "Military Maps",      lcsh: "Military maps",               query: "military map OR battle map OR campaign map" },
      { label: "Sea Charts",         lcsh: "Nautical charts",             query: "nautical chart OR sea chart OR portolan chart" },
      { label: "Thematic Maps",      lcsh: "Thematic maps",               query: "thematic map OR statistical map OR choropleth" },
      { label: "Topographic Maps",   lcsh: "Topographic maps",            query: "topographic map OR contour map OR survey map" },
      { label: "Trade Routes",       lcsh: "Trade routes",                query: "trade route map OR Silk Road map OR caravan route" },
      { label: "World Maps",         lcsh: "World maps",                  query: "world map OR world atlas OR global map" },
    ],
  },

  {
    id: "people-society",
    label: "People & Society",
    lcClass: "H",
    icon: lcMark("H"),
    headings: [
      { label: "Agriculture & Farming",     lcsh: "Agriculture",              query: "agriculture OR farming OR rural life OR peasant life" },
      { label: "Civic Life",                lcsh: "Civics",                   query: "civic life OR democracy OR civic engagement OR public assembly" },
      { label: "Costumes & Dress",          lcsh: "Costume",                  query: "costume OR traditional dress OR folk clothing" },
      { label: "Cuisine & Food",            lcsh: "Food",                     query: "cuisine OR food culture OR traditional cooking OR meal" },
      { label: "Education",                 lcsh: "Education",                query: "education OR school OR classroom OR teaching" },
      { label: "Ethnic Groups",             lcsh: "Ethnology",                query: "ethnology OR ethnic group OR cultural community" },
      { label: "Family & Childhood",        lcsh: "Family",                   query: "family life OR childhood OR domestic life" },
      { label: "Festivals & Celebrations",  lcsh: "Festivals",                query: "festival OR celebration OR carnival OR feast day" },
      { label: "Gender & Women's History",  lcsh: "Women--History",           query: "women's history OR gender history OR women in society" },
      { label: "Indigenous Peoples",        lcsh: "Indigenous peoples",       query: "indigenous people OR native people OR aboriginal community" },
      { label: "Labor & Work",              lcsh: "Labor",                    query: "labor OR working people OR occupational life OR factory worker" },
      { label: "Markets & Bazaars",         lcsh: "Markets",                  query: "market OR bazaar OR souk OR farmers market" },
      { label: "Marriage & Wedding",        lcsh: "Marriage",                 query: "wedding OR marriage ceremony OR traditional wedding" },
      { label: "Migration & Diaspora",      lcsh: "Emigration and immigration", query: "migration OR emigration OR diaspora OR immigrant" },
      { label: "Poverty & Welfare",         lcsh: "Poverty",                  query: "poverty OR social welfare OR destitution historical" },
      { label: "Religious Life",            lcsh: "Religious life",           query: "religious life OR worship OR clergy OR monastic life" },
      { label: "Social Movements",          lcsh: "Social movements",         query: "social movement OR civil rights OR protest OR activism" },
      { label: "Sports & Athletics",        lcsh: "Sports",                   query: "sport OR athletics OR Olympic OR athletic competition" },
      { label: "Trade & Commerce",          lcsh: "Commerce",                 query: "commerce OR trade OR merchant OR business history" },
      { label: "Urban Life",                lcsh: "City and town life",       query: "urban life OR city life OR street life" },
    ],
  },

  {
    id: "religion-mythology",
    label: "Religion & Mythology",
    lcClass: "BL",
    icon: lcMark("BL"),
    headings: [
      { label: "Angels & Demons",         lcsh: "Angels",                       query: "angel OR demon OR seraph OR cherub OR religious supernatural" },
      { label: "Buddhism",                lcsh: "Buddhism",                     query: "Buddhism OR Buddhist art OR Buddhist temple OR Buddha statue" },
      { label: "Celtic Mythology",        lcsh: "Mythology, Celtic",            query: "Celtic mythology OR Druid OR Irish folklore" },
      { label: "Christianity",            lcsh: "Christianity",                 query: "Christianity OR Christian art OR Christian symbolism" },
      { label: "Egyptian Mythology",      lcsh: "Mythology, Egyptian",          query: "Egyptian mythology OR Egyptian gods OR ancient Egyptian religion" },
      { label: "Folklore",                lcsh: "Folklore",                     query: "folklore OR folk tale OR legend OR fairy tale" },
      { label: "Greek & Roman Mythology", lcsh: "Mythology, Classical",         query: "classical mythology OR Greek mythology OR Roman mythology" },
      { label: "Hinduism",                lcsh: "Hinduism",                     query: "Hinduism OR Hindu art OR Hindu temple OR Hindu deity" },
      { label: "Indigenous Religions",    lcsh: "Indigenous peoples--Religion", query: "indigenous religion OR shamanism OR animism" },
      { label: "Islam",                   lcsh: "Islam",                        query: "Islam OR Islamic art OR Islamic manuscript" },
      { label: "Judaism",                 lcsh: "Judaism",                      query: "Judaism OR Jewish art OR Jewish manuscript OR Torah" },
      { label: "Mythological Creatures",  lcsh: "Animals, Mythical",            query: "mythological creature OR mythical animal OR fantastic beast OR dragon" },
      { label: "Norse Mythology",         lcsh: "Mythology, Norse",             query: "Norse mythology OR Viking mythology OR Nordic gods" },
      { label: "Pilgrimages",             lcsh: "Pilgrims and pilgrimages",     query: "pilgrimage OR pilgrim OR shrine OR holy site" },
      { label: "Religious Ceremonies",    lcsh: "Rites and ceremonies",         query: "religious ceremony OR rite OR ritual worship" },
      { label: "Sacred Texts",            lcsh: "Sacred books",                 query: "sacred text OR religious manuscript OR holy book OR scripture" },
      { label: "Saints & Martyrs",        lcsh: "Christian saints",             query: "saint OR martyr OR hagiography OR icon of saint" },
      { label: "Shinto",                  lcsh: "Shinto",                       query: "Shinto OR Shinto shrine OR torii OR Japanese religion" },
      { label: "Sikhism",                 lcsh: "Sikhism",                      query: "Sikhism OR Sikh art OR gurdwara OR Sikh history" },
      { label: "Taoism & Confucianism",   lcsh: "Taoism",                       query: "Taoism OR Confucianism OR Chinese philosophy OR Tao" },
    ],
  },

  {
    id: "science-technology",
    label: "Science & Technology",
    lcClass: "T",
    icon: lcMark("T"),
    headings: [
      { label: "Agriculture Technology", lcsh: "Agricultural innovations",             query: "agricultural technology OR farm machinery OR irrigation system" },
      { label: "Aviation",               lcsh: "Aeronautics",                          query: "aviation OR aeronautics OR aircraft history OR early flight" },
      { label: "Chemistry",              lcsh: "Chemistry",                            query: "chemistry OR chemical apparatus OR laboratory chemistry" },
      { label: "Computing & Electronics", lcsh: "Computers",                           query: "computer OR electronics OR computing history" },
      { label: "Electricity",            lcsh: "Electric engineering",                 query: "electricity OR electrical engineering OR power generation history" },
      { label: "Engineering",            lcsh: "Engineering",                          query: "engineering OR civil engineering OR mechanical engineering" },
      { label: "Human Anatomy",          lcsh: "Human anatomy",                        query: "human anatomy OR anatomical illustration OR body systems" },
      { label: "Industrial Revolution",  lcsh: "Industrial revolution",                query: "industrial revolution OR industrialization OR factory history" },
      { label: "Inventions",             lcsh: "Inventions",                           query: "invention OR inventor OR patent drawing OR historic invention" },
      { label: "Mathematics",            lcsh: "Mathematics",                          query: "mathematics OR mathematical diagram OR geometry" },
      { label: "Medicine & Surgery",     lcsh: "Medicine",                             query: "medicine OR surgery OR medical history OR clinical illustration" },
      { label: "Mining & Metallurgy",    lcsh: "Mining engineering",                   query: "mining OR metallurgy OR ore extraction OR foundry" },
      { label: "Optics & Microscopy",    lcsh: "Optics",                               query: "optics OR microscope OR microscopy OR lens" },
      { label: "Physics",                lcsh: "Physics",                              query: "physics OR physical science OR mechanics" },
      { label: "Robotics & Automation",  lcsh: "Robotics",                             query: "robot OR automaton OR robotics history" },
      { label: "Scientific Instruments", lcsh: "Scientific apparatus and instruments", query: "scientific instrument OR laboratory apparatus OR measuring instrument" },
      { label: "Shipbuilding & Navigation", lcsh: "Shipbuilding",                      query: "shipbuilding OR navigation OR maritime technology OR historic ship" },
      { label: "Steam Engines",          lcsh: "Steam-engines",                        query: "steam engine OR locomotive OR steam power" },
      { label: "Telecommunications",     lcsh: "Telecommunication",                    query: "telecommunications OR telegraph OR telephone OR radio history" },
      { label: "Transportation",         lcsh: "Transportation",                       query: "transportation OR vehicle OR locomotion OR historic transport" },
    ],
  },

];
