/* ─────────────────────────────────────────────────────────────────
   Browse-by-Topic taxonomy (12 categories).
   Each topic:    { id, label, lcClass, icon, headings[] }
   Each heading:  { label, lcsh, query }
   The lcsh and lcClass fields are metadata kept for backend / future
   API integrations — they are not displayed in the UI.
   ───────────────────────────────────────────────────────────────── */

export const TOPICS = [

  {
    id: "natural-history",
    label: "Natural History",
    lcClass: "Q",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="40" height="40" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19.2 2.96a1 1 0 0 1 1.8.66c0 1.93-.16 5.32-1.38 8.27-1.45 3.55-4.49 5.91-8.62 6.11Z"/><path d="M2 21c0-3 1.85-5.36 5.08-6"/></svg>`,
    headings: [
      { label: "Mammals",                        lcsh: "Mammals",                  query: "mammals OR mammalia OR wildlife mammals" },
      { label: "Marine Mammals",                 lcsh: "Marine mammals",           query: "whales OR dolphins OR seals OR marine mammals" },
      { label: "Birds",                          lcsh: "Birds",                    query: "birds OR aves OR ornithology" },
      { label: "Bird Songs",                     lcsh: "Birdsongs",                query: "bird song OR birdsong OR bird call" },
      { label: "Reptiles & Amphibians",          lcsh: "Reptiles",                 query: "reptiles OR amphibians OR herpetology" },
      { label: "Fish",                           lcsh: "Fishes",                   query: "fishes OR fish species OR ichthyology" },
      { label: "Insects",                        lcsh: "Insects",                  query: "insects OR entomology OR insecta" },
      { label: "Arachnids",                      lcsh: "Arachnida",                query: "spider OR arachnid OR scorpion" },
      { label: "Mollusks",                       lcsh: "Mollusks",                 query: "mollusk OR snail OR octopus OR nautilus" },
      { label: "Crustaceans",                    lcsh: "Crustacea",                query: "crustacean OR crab OR lobster OR shrimp" },
      { label: "Marine Life",                    lcsh: "Marine animals",           query: "marine animals OR sea creatures OR ocean life" },
      { label: "Flowering Plants",               lcsh: "Angiosperms",              query: "flowering plants OR angiosperms OR wildflowers" },
      { label: "Trees & Shrubs",                 lcsh: "Trees",                    query: "trees OR shrubs OR dendrology" },
      { label: "Mosses & Ferns",                 lcsh: "Mosses",                   query: "moss OR fern OR bryophyte OR pteridophyte" },
      { label: "Fungi & Lichens",                lcsh: "Fungi",                    query: "fungi OR mushrooms OR lichens" },
      { label: "Fossils & Paleontology",         lcsh: "Paleontology",             query: "fossils OR paleontology OR prehistoric life" },
      { label: "Ecology & Habitats",             lcsh: "Ecology",                  query: "ecology OR habitat OR ecosystem OR biome" },
      { label: "Animal Behavior",                lcsh: "Animal behavior",          query: "animal behavior OR ethology OR animal social behavior" },
      { label: "Wildlife Photography",           lcsh: "Wildlife photography",     query: "wildlife photography OR nature photography" },
      { label: "Conservation & Endangered Species", lcsh: "Endangered species",    query: "endangered species OR wildlife conservation OR rare species" },
    ],
  },

  {
    id: "landscapes-earth",
    label: "Landscapes & Earth",
    lcClass: "G",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="40" height="40" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m8 3 4 8 5-5 5 15H2L8 3z"/><path d="M4.14 15.08c2.62-1.57 5.24-1.43 7.86.42 2.74 1.94 5.49 2 8.23.19"/></svg>`,
    headings: [
      { label: "Mountains",            lcsh: "Mountains",            query: "mountains OR mountain range OR alpine landscape" },
      { label: "Canyons & Valleys",    lcsh: "Canyons",              query: "canyon OR valley OR gorge OR ravine" },
      { label: "Cliffs",               lcsh: "Cliffs",               query: "cliff OR sea cliff OR escarpment" },
      { label: "Rivers & Streams",     lcsh: "Rivers",               query: "rivers OR streams OR waterways" },
      { label: "Lakes",                lcsh: "Lakes",                query: "lake OR alpine lake OR mountain lake" },
      { label: "Waterfalls",           lcsh: "Waterfalls",           query: "waterfall OR cascade OR falls" },
      { label: "Coasts & Shorelines",  lcsh: "Coasts",               query: "coasts OR shoreline OR coastal landscape" },
      { label: "Islands",              lcsh: "Islands",              query: "islands OR island geography OR archipelago" },
      { label: "Deserts",              lcsh: "Deserts",              query: "deserts OR arid landscape OR desert terrain" },
      { label: "Forests",              lcsh: "Forests and forestry", query: "forests OR woodland OR forest landscape" },
      { label: "Rainforests",          lcsh: "Rain forests",         query: "rainforest OR tropical forest OR jungle" },
      { label: "Savanna & Grasslands", lcsh: "Grasslands",           query: "savanna OR grassland OR prairie OR steppe" },
      { label: "Tundra",               lcsh: "Tundras",              query: "tundra OR arctic landscape OR taiga" },
      { label: "Wetlands",             lcsh: "Wetlands",             query: "wetlands OR marshes OR swamps OR bogs" },
      { label: "Glaciers & Ice",       lcsh: "Glaciers",             query: "glaciers OR ice sheets OR iceberg OR polar landscape" },
      { label: "Volcanoes",            lcsh: "Volcanoes",            query: "volcanoes OR volcanic eruption OR lava OR caldera" },
      { label: "Caves",                lcsh: "Caves",                query: "caves OR caverns OR speleology" },
      { label: "Aerial Views",         lcsh: "Aerial photography",   query: "aerial photography OR aerial view OR landscape from above" },
    ],
  },

  {
    id: "astronomy",
    label: "Astronomy",
    lcClass: "QB",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="40" height="40" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m10.065 12.493-6.18 1.318a.934.934 0 0 1-1.108-.702l-.537-2.15a1.07 1.07 0 0 1 .691-1.265l13.504-4.44"/><path d="m13.56 11.747 4.332-.924"/><path d="m16 21-3.105-6.21"/><path d="M16.485 5.94a2 2 0 0 1 1.455-2.425l1.09-.272a1 1 0 0 1 1.212.727l1.515 6.06a1 1 0 0 1-.727 1.213l-1.09.272a2 2 0 0 1-2.425-1.455z"/><path d="m6.158 8.633 1.114 4.456"/><path d="m8 21 3.105-6.21"/><circle cx="12" cy="13" r="2"/></svg>`,
    headings: [
      { label: "Solar System",              lcsh: "Solar system",       query: "solar system OR planets OR planetary science" },
      { label: "The Sun",                   lcsh: "Sun",                query: "sun OR solar corona OR sunspot" },
      { label: "The Moon",                  lcsh: "Moon",               query: "moon OR lunar surface OR lunar geology" },
      { label: "Mars",                      lcsh: "Mars (Planet)",      query: "Mars planet OR Martian surface OR Mars exploration" },
      { label: "Jupiter & Saturn",          lcsh: "Jupiter (Planet)",   query: "Jupiter OR Saturn OR gas giant" },
      { label: "Stars",                     lcsh: "Stars",              query: "stars OR stellar OR star cluster" },
      { label: "Constellations",            lcsh: "Constellations",     query: "constellations OR star map OR celestial chart" },
      { label: "Galaxies",                  lcsh: "Galaxies",           query: "galaxies OR galaxy OR extragalactic" },
      { label: "Nebulae",                   lcsh: "Nebulae",            query: "nebulae OR nebula OR interstellar cloud" },
      { label: "Black Holes",               lcsh: "Black holes (Astronomy)", query: "black hole OR event horizon OR singularity" },
      { label: "Supernovas",                lcsh: "Supernovae",         query: "supernova OR stellar explosion OR exploding star" },
      { label: "Comets & Asteroids",        lcsh: "Comets",             query: "comets OR asteroids OR minor planets OR meteorites" },
      { label: "Exoplanets",                lcsh: "Extrasolar planets", query: "exoplanet OR extrasolar planet OR alien world" },
      { label: "Cosmology",                 lcsh: "Cosmology",          query: "cosmology OR universe OR big bang OR cosmic background" },
      { label: "Telescopes & Observatories", lcsh: "Telescopes",        query: "telescope OR observatory OR astronomical instrument" },
      { label: "Space Exploration",         lcsh: "Astronautics",       query: "space exploration OR spacecraft OR space mission" },
      { label: "Astronauts",                lcsh: "Astronauts",         query: "astronaut OR cosmonaut OR human spaceflight" },
      { label: "Astrophotography",          lcsh: "Astronomical photography", query: "astrophotography OR deep space photo OR night sky photography" },
    ],
  },

  {
    id: "fine-arts",
    label: "Fine Arts",
    lcClass: "N",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="40" height="40" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="13.5" cy="6.5" r=".5" fill="currentColor"/><circle cx="17.5" cy="10.5" r=".5" fill="currentColor"/><circle cx="8.5" cy="7.5" r=".5" fill="currentColor"/><circle cx="6.5" cy="12.5" r=".5" fill="currentColor"/><path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2z"/></svg>`,
    headings: [
      { label: "Painting",              lcsh: "Painting",                     query: "painting OR oil painting OR canvas art" },
      { label: "Watercolor",            lcsh: "Watercolor painting",          query: "watercolor OR watercolour OR aquarelle" },
      { label: "Pastels",               lcsh: "Pastel drawing",               query: "pastel drawing OR pastel painting OR chalk pastel" },
      { label: "Drawing & Sketching",   lcsh: "Drawing",                      query: "drawing OR sketch OR charcoal art" },
      { label: "Printmaking",           lcsh: "Prints",                       query: "prints OR printmaking OR engraving OR etching OR woodcut" },
      { label: "Sculpture",             lcsh: "Sculpture",                    query: "sculpture OR sculptural art OR statue OR carving" },
      { label: "Frescoes",              lcsh: "Mural painting and decoration", query: "fresco OR fresco painting OR Italian fresco" },
      { label: "Murals",                lcsh: "Mural painting and decoration", query: "mural OR wall painting OR public mural" },
      { label: "Mosaics",               lcsh: "Mosaics",                      query: "mosaic OR tessera OR Byzantine mosaic OR Roman mosaic" },
      { label: "Calligraphy",           lcsh: "Calligraphy",                  query: "calligraphy OR Islamic calligraphy OR Chinese calligraphy" },
      { label: "Portrait Art",          lcsh: "Portrait painting",            query: "portrait painting OR portraiture OR painted portrait" },
      { label: "Landscape Painting",    lcsh: "Landscape painting",           query: "landscape painting OR landscape art OR plein air" },
      { label: "Still Life",            lcsh: "Still-life painting",          query: "still life OR still-life painting OR nature morte" },
      { label: "Genre Painting",        lcsh: "Genre painting",               query: "genre painting OR everyday life painting" },
      { label: "History Painting",      lcsh: "History painting",             query: "history painting OR historical painting OR battle scene painting" },
      { label: "Religious Art",         lcsh: "Christian art and symbolism",  query: "religious art OR devotional painting OR altarpiece" },
      { label: "Photography (Fine Art)", lcsh: "Photography, Artistic",       query: "artistic photography OR fine art photography" },
      { label: "Illustration",          lcsh: "Illustration of books",        query: "illustration OR book illustration OR decorative illustration" },
      { label: "Caricature",            lcsh: "Caricatures and cartoons",     query: "caricature OR political cartoon OR satirical drawing" },
      { label: "Miniature Painting",    lcsh: "Miniature painting",           query: "miniature painting OR illuminated manuscript OR Persian miniature" },
    ],
  },

  {
    id: "architecture",
    label: "Architecture",
    lcClass: "NA",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="40" height="40" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><line x1="3" x2="21" y1="22" y2="22"/><line x1="6" x2="6" y1="18" y2="11"/><line x1="10" x2="10" y1="18" y2="11"/><line x1="14" x2="14" y1="18" y2="11"/><line x1="18" x2="18" y1="18" y2="11"/><polygon points="12 2 20 7 4 7"/></svg>`,
    headings: [
      { label: "Ancient Architecture",      lcsh: "Architecture, Ancient",     query: "ancient architecture OR Greek temple OR Roman architecture" },
      { label: "Egyptian Architecture",     lcsh: "Architecture, Egyptian",    query: "Egyptian architecture OR pyramid OR ancient Egyptian temple" },
      { label: "Asian Architecture",        lcsh: "Architecture, East Asian",  query: "Asian architecture OR pagoda OR Chinese architecture OR Japanese architecture" },
      { label: "Medieval Architecture",     lcsh: "Architecture, Medieval",    query: "medieval architecture OR gothic cathedral OR romanesque" },
      { label: "Renaissance Architecture",  lcsh: "Architecture, Renaissance", query: "Renaissance architecture OR classical revival OR palazzo" },
      { label: "Baroque Architecture",      lcsh: "Architecture, Baroque",     query: "baroque architecture OR baroque church OR baroque palace" },
      { label: "Islamic Architecture",      lcsh: "Architecture, Islamic",     query: "Islamic architecture OR mosque OR madrasa OR minaret" },
      { label: "Vernacular Architecture",   lcsh: "Vernacular architecture",   query: "vernacular architecture OR traditional building OR folk architecture" },
      { label: "Castles & Fortifications",  lcsh: "Castles",                   query: "castle OR fortification OR medieval fortress" },
      { label: "Churches & Cathedrals",     lcsh: "Church architecture",       query: "church OR cathedral OR basilica" },
      { label: "Mosques",                   lcsh: "Mosques",                   query: "mosque OR jami OR masjid OR Islamic place of worship" },
      { label: "Domestic Architecture",     lcsh: "Architecture, Domestic",    query: "domestic architecture OR historic house OR manor house" },
      { label: "Civic Buildings",           lcsh: "Public buildings",          query: "public building OR civic architecture OR city hall" },
      { label: "Bridges",                   lcsh: "Bridges",                   query: "bridge OR historic bridge OR stone bridge OR viaduct" },
      { label: "Lighthouses",               lcsh: "Lighthouses",               query: "lighthouse OR coastal lighthouse OR maritime beacon" },
      { label: "Towers",                    lcsh: "Towers",                    query: "tower OR bell tower OR clock tower OR watchtower" },
      { label: "Modern Architecture",       lcsh: "Architecture, Modern",      query: "modern architecture OR modernist building OR 20th century architecture" },
      { label: "Art Nouveau",               lcsh: "Architecture, Art nouveau", query: "Art Nouveau architecture OR Jugendstil OR Secession architecture" },
      { label: "Art Deco",                  lcsh: "Architecture, Art deco",    query: "Art Deco architecture OR Streamline Moderne" },
      { label: "Architectural Drawings",    lcsh: "Architectural drawing",    query: "architectural drawing OR blueprint OR architectural rendering" },
    ],
  },

  {
    id: "decorative-arts",
    label: "Decorative Arts",
    lcClass: "NK",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="40" height="40" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6 3h12l4 6-10 13L2 9Z"/><path d="M11 3 8 9l4 13 4-13-3-6"/><path d="M2 9h20"/></svg>`,
    headings: [
      { label: "Ceramics & Pottery",     lcsh: "Ceramics",              query: "ceramics OR pottery OR earthenware OR porcelain" },
      { label: "Furniture",              lcsh: "Furniture",             query: "furniture OR historic furniture OR antique furniture" },
      { label: "Textiles & Weaving",     lcsh: "Textile fabrics",       query: "textile OR woven fabric OR weaving" },
      { label: "Tapestries",             lcsh: "Tapestry",              query: "tapestry OR woven tapestry OR Flemish tapestry" },
      { label: "Quilts",                 lcsh: "Quilts",                query: "quilt OR patchwork quilt OR American quilt" },
      { label: "Embroidery & Needlework", lcsh: "Embroidery",           query: "embroidery OR needlework OR decorative stitching" },
      { label: "Lacework",               lcsh: "Lace and lace making",  query: "lace OR lacework OR bobbin lace OR needle lace" },
      { label: "Rugs & Carpets",         lcsh: "Rugs",                  query: "rug OR carpet OR oriental rug OR Persian carpet" },
      { label: "Glassware",              lcsh: "Glassware",             query: "glassware OR art glass OR decorative glass" },
      { label: "Stained Glass",          lcsh: "Glass painting and staining", query: "stained glass OR leaded glass OR church window" },
      { label: "Jewelry",                lcsh: "Jewelry",               query: "jewelry OR jewellery OR ornamental adornment" },
      { label: "Metalwork",              lcsh: "Metal-work",            query: "metalwork OR wrought iron OR decorative metalwork" },
      { label: "Wood Carving",           lcsh: "Wood-carving",          query: "wood carving OR woodwork OR carved wood" },
      { label: "Lacquerwork",            lcsh: "Lacquer and lacquering", query: "lacquerwork OR lacquer art OR Japanese lacquer" },
      { label: "Cloisonné & Enamels",    lcsh: "Enamel and enameling",  query: "cloisonné OR enamel OR champlevé" },
      { label: "Coins & Medals",         lcsh: "Coins",                 query: "coin OR medal OR ancient coin OR commemorative medal" },
      { label: "Watches & Clocks",       lcsh: "Clocks and watches",    query: "clock OR watch OR timepiece OR antique clock" },
      { label: "Arms & Armor",           lcsh: "Arms and armor",        query: "arms and armor OR sword OR helmet OR historic weapon" },
      { label: "Bookbinding",            lcsh: "Bookbinding",           query: "bookbinding OR decorative binding OR historic bookcover" },
    ],
  },

  {
    id: "music",
    label: "Music",
    lcClass: "M",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="40" height="40" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/></svg>`,
    headings: [
      { label: "String Instruments",      lcsh: "Stringed instruments",   query: "stringed instrument OR violin OR cello OR lute" },
      { label: "Wind Instruments",        lcsh: "Wind instruments",       query: "wind instrument OR flute OR oboe OR clarinet" },
      { label: "Brass Instruments",       lcsh: "Brass instruments",      query: "brass instrument OR trumpet OR trombone OR horn" },
      { label: "Percussion Instruments",  lcsh: "Percussion instruments", query: "percussion instrument OR drum OR xylophone OR timpani" },
      { label: "Keyboard Instruments",    lcsh: "Keyboard instruments",   query: "keyboard instrument OR piano OR harpsichord OR organ" },
      { label: "Folk Music",              lcsh: "Folk music",             query: "folk music OR traditional music OR world music" },
      { label: "Classical Music",         lcsh: "Music",                  query: "classical music OR orchestral music OR concert music" },
      { label: "Sacred & Choral Music",   lcsh: "Sacred music",           query: "sacred music OR choral music OR hymn OR Gregorian chant" },
      { label: "Opera",                   lcsh: "Opera",                  query: "opera OR operatic performance OR opera house" },
      { label: "Operetta & Musical Theater", lcsh: "Musicals",            query: "operetta OR musical theater OR Broadway musical" },
      { label: "Jazz & Blues",            lcsh: "Jazz",                   query: "jazz OR blues OR jazz band OR jazz musician" },
      { label: "Ballet & Dance",          lcsh: "Ballet",                 query: "ballet OR classical dance OR dance performance" },
      { label: "Music Manuscripts",       lcsh: "Music manuscripts",      query: "music manuscript OR musical score OR sheet music" },
      { label: "Musical Notation",        lcsh: "Musical notation",       query: "musical notation OR music score OR notated music" },
      { label: "Concerts & Performances", lcsh: "Concerts",               query: "concert OR music performance OR recital" },
      { label: "Musical Ensembles",       lcsh: "Musical ensembles",      query: "orchestra OR musical ensemble OR chamber music" },
      { label: "Marching Bands",          lcsh: "Bands (Music)",          query: "marching band OR military band OR brass band" },
      { label: "Music History",           lcsh: "Music--History",         query: "music history OR historical musicology OR composer portrait" },
    ],
  },

  {
    id: "history",
    label: "History",
    lcClass: "D",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="40" height="40" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M15 12h-5"/><path d="M15 8h-5"/><path d="M19 17V5a2 2 0 0 0-2-2H4"/><path d="M8 21h12a2 2 0 0 0 2-2v-1a1 1 0 0 0-1-1H11a1 1 0 0 0-1 1v1a2 2 0 1 1-4 0V5a2 2 0 1 0-4 0v2a1 1 0 0 0 1 1h3"/></svg>`,
    headings: [
      { label: "Ancient Civilizations",      lcsh: "Civilization, Ancient",        query: "ancient civilization OR ancient world OR antiquity" },
      { label: "Ancient Egypt",              lcsh: "Egypt--Civilization",          query: "ancient Egypt OR Egyptian civilization OR pharaonic Egypt" },
      { label: "Ancient Greece",             lcsh: "Greece--History--To 146 B.C.", query: "ancient Greece OR Greek history OR Hellenic civilization" },
      { label: "Ancient Rome",               lcsh: "Rome--History",                query: "ancient Rome OR Roman history OR Roman Empire" },
      { label: "Vikings",                    lcsh: "Vikings",                      query: "Vikings OR Norse OR Viking Age" },
      { label: "Medieval Period",            lcsh: "Middle Ages",                  query: "Middle Ages OR medieval history OR medieval Europe" },
      { label: "Crusades",                   lcsh: "Crusades",                     query: "Crusades OR crusader OR medieval Holy Land" },
      { label: "Byzantine Empire",           lcsh: "Byzantine Empire",             query: "Byzantine Empire OR Constantinople OR Eastern Roman" },
      { label: "Renaissance & Reformation",  lcsh: "Renaissance",                  query: "Renaissance OR Reformation OR Protestant Reformation" },
      { label: "Age of Exploration",         lcsh: "Discoveries (in geography)",   query: "age of exploration OR voyage of discovery OR explorers" },
      { label: "Colonial History",           lcsh: "Colonies",                     query: "colonial history OR colonialism OR colonial era" },
      { label: "Revolutions",                lcsh: "Revolutions",                  query: "revolution OR revolutionary war OR political revolution" },
      { label: "American History",           lcsh: "United States--History",       query: "American history OR United States history OR US historical" },
      { label: "Latin American History",     lcsh: "Latin America--History",       query: "Latin American history OR South American history OR pre-Columbian" },
      { label: "African History",            lcsh: "Africa--History",              query: "African history OR sub-Saharan Africa history OR African civilization" },
      { label: "Asian History",              lcsh: "Asia--History",                query: "Asian history OR East Asia history OR Asian civilization" },
      { label: "Russian History",            lcsh: "Russia--History",              query: "Russian history OR Imperial Russia OR Soviet Union history" },
      { label: "World War I",                lcsh: "World War, 1914-1918",         query: "World War I OR First World War OR WWI" },
      { label: "World War II",               lcsh: "World War, 1939-1945",         query: "World War II OR Second World War OR WWII" },
      { label: "Cold War",                   lcsh: "Cold War",                     query: "Cold War OR Iron Curtain OR Soviet-American" },
    ],
  },

  {
    id: "maps-cartography",
    label: "Maps & Cartography",
    lcClass: "GA",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="40" height="40" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z"/><circle cx="12" cy="12" r="10"/></svg>`,
    headings: [
      { label: "World Maps",         lcsh: "World maps",                  query: "world map OR world atlas OR global map" },
      { label: "Historical Maps",    lcsh: "Historical maps",             query: "historical map OR antique map OR old map" },
      { label: "Maps of Antiquity",  lcsh: "Cartography, Ancient",        query: "ancient map OR Ptolemy map OR Roman cartography" },
      { label: "Manuscript Maps",    lcsh: "Maps, Manuscript",            query: "manuscript map OR hand-drawn map OR cartographic manuscript" },
      { label: "Topographic Maps",   lcsh: "Topographic maps",            query: "topographic map OR contour map OR survey map" },
      { label: "Sea Charts",         lcsh: "Nautical charts",             query: "nautical chart OR sea chart OR portolan chart" },
      { label: "Aviation Charts",    lcsh: "Aeronautical charts",         query: "aeronautical chart OR aviation map OR sectional chart" },
      { label: "Military Maps",      lcsh: "Military maps",               query: "military map OR battle map OR campaign map" },
      { label: "City Plans",         lcsh: "Cities and towns--Maps",      query: "city map OR city plan OR urban cartography" },
      { label: "Celestial Charts",   lcsh: "Stars--Maps",                 query: "celestial map OR star chart OR astronomical map" },
      { label: "Map Projections",    lcsh: "Map projection",              query: "map projection OR Mercator OR Robinson projection" },
      { label: "Thematic Maps",      lcsh: "Thematic maps",               query: "thematic map OR statistical map OR choropleth" },
      { label: "Trade Routes",       lcsh: "Trade routes",                query: "trade route map OR Silk Road map OR caravan route" },
      { label: "Atlas Pages",        lcsh: "Atlases",                     query: "atlas OR geographic atlas OR cartographic atlas" },
      { label: "Globes",             lcsh: "Globes",                      query: "globe OR terrestrial globe OR celestial globe" },
      { label: "Cartographic Art",   lcsh: "Decorative maps",             query: "decorative map OR cartouche OR ornamental map" },
    ],
  },

  {
    id: "people-society",
    label: "People & Society",
    lcClass: "H",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="40" height="40" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>`,
    headings: [
      { label: "Indigenous Peoples",        lcsh: "Indigenous peoples",       query: "indigenous people OR native people OR aboriginal community" },
      { label: "Ethnic Groups",             lcsh: "Ethnology",                query: "ethnology OR ethnic group OR cultural community" },
      { label: "Costumes & Dress",          lcsh: "Costume",                  query: "costume OR traditional dress OR folk clothing" },
      { label: "Family & Childhood",        lcsh: "Family",                   query: "family life OR childhood OR domestic life" },
      { label: "Education",                 lcsh: "Education",                query: "education OR school OR classroom OR teaching" },
      { label: "Religious Life",            lcsh: "Religious life",           query: "religious life OR worship OR clergy OR monastic life" },
      { label: "Civic Life",                lcsh: "Civics",                   query: "civic life OR democracy OR civic engagement OR public assembly" },
      { label: "Labor & Work",              lcsh: "Labor",                    query: "labor OR working people OR occupational life OR factory worker" },
      { label: "Agriculture & Farming",     lcsh: "Agriculture",              query: "agriculture OR farming OR rural life OR peasant life" },
      { label: "Trade & Commerce",          lcsh: "Commerce",                 query: "commerce OR trade OR merchant OR business history" },
      { label: "Markets & Bazaars",         lcsh: "Markets",                  query: "market OR bazaar OR souk OR farmers market" },
      { label: "Cuisine & Food",            lcsh: "Food",                     query: "cuisine OR food culture OR traditional cooking OR meal" },
      { label: "Festivals & Celebrations",  lcsh: "Festivals",                query: "festival OR celebration OR carnival OR feast day" },
      { label: "Sports & Athletics",        lcsh: "Sports",                   query: "sport OR athletics OR Olympic OR athletic competition" },
      { label: "Marriage & Wedding",        lcsh: "Marriage",                 query: "wedding OR marriage ceremony OR traditional wedding" },
      { label: "Migration & Diaspora",      lcsh: "Emigration and immigration", query: "migration OR emigration OR diaspora OR immigrant" },
      { label: "Social Movements",          lcsh: "Social movements",         query: "social movement OR civil rights OR protest OR activism" },
      { label: "Gender & Women's History",  lcsh: "Women--History",           query: "women's history OR gender history OR women in society" },
      { label: "Urban Life",                lcsh: "City and town life",       query: "urban life OR city life OR street life" },
      { label: "Poverty & Welfare",         lcsh: "Poverty",                  query: "poverty OR social welfare OR destitution historical" },
    ],
  },

  {
    id: "religion-mythology",
    label: "Religion & Mythology",
    lcClass: "BL",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="40" height="40" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M10 9h4"/><path d="M12 7v5"/><path d="M14 22v-4a2 2 0 0 0-2-2a2 2 0 0 0-2 2v4"/><path d="M18 22V5.618a1 1 0 0 0-.553-.894l-4.553-2.277a2 2 0 0 0-1.788 0L6.553 4.724A1 1 0 0 0 6 5.618V22"/><path d="m18 7 3.447 1.724a1 1 0 0 1 .553.894V20a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9.618a1 1 0 0 1 .553-.894L6 7"/></svg>`,
    headings: [
      { label: "Greek & Roman Mythology", lcsh: "Mythology, Classical",        query: "classical mythology OR Greek mythology OR Roman mythology" },
      { label: "Norse Mythology",         lcsh: "Mythology, Norse",            query: "Norse mythology OR Viking mythology OR Nordic gods" },
      { label: "Egyptian Mythology",      lcsh: "Mythology, Egyptian",         query: "Egyptian mythology OR Egyptian gods OR ancient Egyptian religion" },
      { label: "Celtic Mythology",        lcsh: "Mythology, Celtic",           query: "Celtic mythology OR Druid OR Irish folklore" },
      { label: "Christianity",            lcsh: "Christianity",                query: "Christianity OR Christian art OR Christian symbolism" },
      { label: "Islam",                   lcsh: "Islam",                       query: "Islam OR Islamic art OR Islamic manuscript" },
      { label: "Judaism",                 lcsh: "Judaism",                     query: "Judaism OR Jewish art OR Jewish manuscript OR Torah" },
      { label: "Hinduism",                lcsh: "Hinduism",                    query: "Hinduism OR Hindu art OR Hindu temple OR Hindu deity" },
      { label: "Buddhism",                lcsh: "Buddhism",                    query: "Buddhism OR Buddhist art OR Buddhist temple OR Buddha statue" },
      { label: "Sikhism",                 lcsh: "Sikhism",                     query: "Sikhism OR Sikh art OR gurdwara OR Sikh history" },
      { label: "Taoism & Confucianism",   lcsh: "Taoism",                      query: "Taoism OR Confucianism OR Chinese philosophy OR Tao" },
      { label: "Shinto",                  lcsh: "Shinto",                      query: "Shinto OR Shinto shrine OR torii OR Japanese religion" },
      { label: "Indigenous Religions",    lcsh: "Indigenous peoples--Religion", query: "indigenous religion OR shamanism OR animism" },
      { label: "Sacred Texts",            lcsh: "Sacred books",                query: "sacred text OR religious manuscript OR holy book OR scripture" },
      { label: "Religious Ceremonies",    lcsh: "Rites and ceremonies",        query: "religious ceremony OR rite OR ritual worship" },
      { label: "Saints & Martyrs",        lcsh: "Christian saints",            query: "saint OR martyr OR hagiography OR icon of saint" },
      { label: "Angels & Demons",         lcsh: "Angels",                      query: "angel OR demon OR seraph OR cherub OR religious supernatural" },
      { label: "Pilgrimages",             lcsh: "Pilgrims and pilgrimages",    query: "pilgrimage OR pilgrim OR shrine OR holy site" },
      { label: "Mythological Creatures",  lcsh: "Animals, Mythical",           query: "mythological creature OR mythical animal OR fantastic beast OR dragon" },
      { label: "Folklore",                lcsh: "Folklore",                    query: "folklore OR folk tale OR legend OR fairy tale" },
    ],
  },

  {
    id: "science-technology",
    label: "Science & Technology",
    lcClass: "T",
    icon: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="40" height="40" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 2v6a2 2 0 0 0 .245.96l5.51 10.08A2 2 0 0 1 18 22H6a2 2 0 0 1-1.755-2.96l5.51-10.08A2 2 0 0 0 10 8V2"/><path d="M6.453 15h11.094"/><path d="M8.5 2h7"/></svg>`,
    headings: [
      { label: "Scientific Instruments", lcsh: "Scientific apparatus and instruments", query: "scientific instrument OR laboratory apparatus OR measuring instrument" },
      { label: "Chemistry",              lcsh: "Chemistry",                            query: "chemistry OR chemical apparatus OR laboratory chemistry" },
      { label: "Physics",                lcsh: "Physics",                              query: "physics OR physical science OR mechanics" },
      { label: "Mathematics",            lcsh: "Mathematics",                          query: "mathematics OR mathematical diagram OR geometry" },
      { label: "Optics & Microscopy",    lcsh: "Optics",                               query: "optics OR microscope OR microscopy OR lens" },
      { label: "Medicine & Surgery",     lcsh: "Medicine",                             query: "medicine OR surgery OR medical history OR clinical illustration" },
      { label: "Human Anatomy",          lcsh: "Human anatomy",                        query: "human anatomy OR anatomical illustration OR body systems" },
      { label: "Engineering",            lcsh: "Engineering",                          query: "engineering OR civil engineering OR mechanical engineering" },
      { label: "Transportation",         lcsh: "Transportation",                       query: "transportation OR vehicle OR locomotion OR historic transport" },
      { label: "Aviation",               lcsh: "Aeronautics",                          query: "aviation OR aeronautics OR aircraft history OR early flight" },
      { label: "Shipbuilding & Navigation", lcsh: "Shipbuilding",                      query: "shipbuilding OR navigation OR maritime technology OR historic ship" },
      { label: "Telecommunications",     lcsh: "Telecommunication",                    query: "telecommunications OR telegraph OR telephone OR radio history" },
      { label: "Industrial Revolution",  lcsh: "Industrial revolution",                query: "industrial revolution OR industrialization OR factory history" },
      { label: "Steam Engines",          lcsh: "Steam-engines",                        query: "steam engine OR locomotive OR steam power" },
      { label: "Computing & Electronics", lcsh: "Computers",                           query: "computer OR electronics OR computing history" },
      { label: "Electricity",            lcsh: "Electric engineering",                 query: "electricity OR electrical engineering OR power generation history" },
      { label: "Agriculture Technology", lcsh: "Agricultural innovations",             query: "agricultural technology OR farm machinery OR irrigation system" },
      { label: "Mining & Metallurgy",    lcsh: "Mining engineering",                   query: "mining OR metallurgy OR ore extraction OR foundry" },
      { label: "Inventions",             lcsh: "Inventions",                           query: "invention OR inventor OR patent drawing OR historic invention" },
      { label: "Robotics & Automation",  lcsh: "Robotics",                             query: "robot OR automaton OR robotics history" },
    ],
  },

];
